process.env.STAGE = 'staging'
process.env.GITHUB_LOGIN_URL = 'https://github.com'
process.env.GITHUB_API_URL = 'https://api.github.com'
process.env.GITHUB_CERT_KEY = 'github.key'
process.env.GITHUB_CERT_PUBLIC = 'github.pub'
